# Generated by Django 5.2.8 on 2025-11-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('medico', 'Médico'), ('matrona', 'Matrona'), ('enfermero', 'Enfermero'), ('administrativo', 'Administrativo'), ('ti', 'Administrador TI'), ('pediatra', 'Pediatra')], max_length=20),
        ),
    ]
