# Generated by Django 5.2.8 on 2025-11-20 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la acción')),
                ('metodo_http', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], help_text='Método HTTP utilizado', max_length=10)),
                ('url', models.CharField(help_text='URL de la petición', max_length=500)),
                ('ruta', models.CharField(blank=True, help_text='Ruta de la vista', max_length=500, null=True)),
                ('nombre_vista', models.CharField(blank=True, help_text='Nombre de la vista', max_length=200, null=True)),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('READ', 'Leer'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('OTHER', 'Otro')], help_text='Tipo de acción realizada', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto afectado', null=True)),
                ('nombre_modelo', models.CharField(blank=True, help_text='Nombre del modelo', max_length=200, null=True)),
                ('datos_enviados', models.JSONField(blank=True, help_text='Datos enviados en la petición', null=True)),
                ('datos_respuesta', models.JSONField(blank=True, help_text='Datos de la respuesta', null=True)),
                ('codigo_respuesta', models.IntegerField(blank=True, help_text='Código HTTP de respuesta', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del cliente', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('exito', models.BooleanField(default=True, help_text='Indica si la acción fue exitosa')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si hubo fallo', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Tipo de modelo afectado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='auditoria_a_fecha_h_b7616a_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='auditoria_a_usuario_e64f3e_idx'), models.Index(fields=['accion', '-fecha_hora'], name='auditoria_a_accion_b0af22_idx'), models.Index(fields=['nombre_modelo', '-fecha_hora'], name='auditoria_a_nombre__6d2600_idx')],
            },
        ),
    ]
