# Generated by Django 5.2.8 on 2025-11-20 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_paciente_hepatitis_b_profilaxis_completa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEnfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_control', models.DateTimeField(auto_now_add=True)),
                ('presion_arterial_sistolica', models.IntegerField(blank=True, help_text='mmHg', null=True)),
                ('presion_arterial_diastolica', models.IntegerField(blank=True, help_text='mmHg', null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, help_text='lpm', null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, help_text='rpm', null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('saturacion_oxigeno', models.IntegerField(blank=True, help_text='%', null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('medicamentos_administrados', models.TextField(blank=True, help_text='Lista de medicamentos administrados', null=True)),
                ('alertas', models.BooleanField(default=False, help_text='Requiere atención especial')),
                ('motivo_alerta', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_enfermeria', to='pacientes.paciente')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de Enfermería',
                'verbose_name_plural': 'Controles de Enfermería',
                'ordering': ['-fecha_control'],
            },
        ),
    ]
