# Generated by Django 5.2.8 on 2025-11-20 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_paciente_hepatitis_b_profilaxis_completa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_consulta', models.DateTimeField(blank=True, null=True)),
                ('motivo_consulta', models.TextField(help_text='Motivo de la consulta')),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(help_text='Diagnóstico médico')),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('examenes_solicitados', models.TextField(blank=True, help_text='Exámenes solicitados', null=True)),
                ('medicamentos_recetados', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('urgente', 'Urgente')], default='pendiente', max_length=20)),
                ('requiere_seguimiento', models.BooleanField(default=False)),
                ('fecha_proxima_consulta', models.DateField(blank=True, null=True)),
                ('medico_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_registrados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_medicos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Reporte Médico',
                'verbose_name_plural': 'Reportes Médicos',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
