# Generated by Django 5.2.8 on 2025-11-20 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_paciente_hepatitis_b_profilaxis_completa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaRecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_egreso', models.DateTimeField(blank=True, help_text='Fecha y hora del egreso', null=True)),
                ('tipo_alta', models.CharField(choices=[('alta_normal', 'Alta Normal'), ('alta_precoz', 'Alta Precoz'), ('traslado', 'Traslado'), ('fallecimiento', 'Fallecimiento')], default='alta_normal', max_length=20)),
                ('condicion_alta', models.CharField(choices=[('buena', 'Buena'), ('regular', 'Regular'), ('grave', 'Grave'), ('critica', 'Crítica')], default='buena', max_length=20)),
                ('diagnostico_final', models.TextField(help_text='Diagnóstico final del recién nacido')),
                ('tratamiento_continuo', models.TextField(blank=True, help_text='Tratamiento a continuar en casa', null=True)),
                ('medicamentos_recetados', models.TextField(blank=True, help_text='Medicamentos recetados', null=True)),
                ('indicaciones_alta', models.TextField(help_text='Indicaciones para el alta')),
                ('controles_programados', models.TextField(blank=True, help_text='Controles programados', null=True)),
                ('vacunas_aplicadas', models.TextField(blank=True, help_text='Vacunas aplicadas durante la estadía', null=True)),
                ('vacunas_pendientes', models.TextField(blank=True, help_text='Vacunas pendientes', null=True)),
                ('tipo_alimentacion', models.CharField(blank=True, help_text='Tipo de alimentación al alta', max_length=100, null=True)),
                ('peso_alta', models.DecimalField(blank=True, decimal_places=2, help_text='Peso al alta (gramos)', max_digits=5, null=True)),
                ('requiere_seguimiento', models.BooleanField(default=False)),
                ('motivo_seguimiento', models.TextField(blank=True, null=True)),
                ('fecha_control_proximo', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('pediatra_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_recien_nacidos', to=settings.AUTH_USER_MODEL)),
                ('recien_nacido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alta', to='pacientes.reciennacido')),
            ],
            options={
                'verbose_name': 'Alta de Recién Nacido',
                'verbose_name_plural': 'Altas de Recién Nacidos',
                'ordering': ['-fecha_alta'],
            },
        ),
    ]
