# Generated by Django 5.2.8 on 2025-11-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('diagnostico', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en Kg', max_digits=5)),
                ('talla', models.DecimalField(decimal_places=1, help_text='Talla en cm', max_digits=4)),
                ('fecha_nacimiento', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('paciente_madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='pacientes.paciente')),
            ],
        ),
    ]
