# Generated by Django 5.2.8 on 2025-11-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cesfam',
            field=models.CharField(blank=True, help_text='Centro de Salud Familiar', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='es_migrante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento de la madre', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hepatitis_b_resultado',
            field=models.CharField(blank=True, help_text='Resultado examen Hepatitis B', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hepatitis_b_tratamiento_ig',
            field=models.CharField(blank=True, help_text='Tratamiento con IG', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pueblo_originario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='vdrl_resultado',
            field=models.CharField(blank=True, help_text='Resultado examen VDRL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='vdrl_tratamiento',
            field=models.CharField(blank=True, help_text='Tratamiento VDRL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='vih_positivo',
            field=models.BooleanField(default=False, help_text='Madre VIH (+)'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='acompanante_pabellon',
            field=models.BooleanField(default=False, help_text='Acompañante en Pabellón'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='alojamiento_conjunto_puerperio',
            field=models.BooleanField(default=False, help_text='Alojamiento Conjunto en Puerperio Inmediato'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='apego',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='apego_canguro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='apego_tunel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='apgar_1min',
            field=models.PositiveIntegerField(blank=True, help_text='APGAR 1 minuto', null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='apgar_5min',
            field=models.PositiveIntegerField(blank=True, help_text='APGAR 5 minutos', null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='circunferencia_cefalica',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='CC en cm', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='clampado_tardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='descripcion_malformacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='destino_rn',
            field=models.CharField(blank=True, help_text='Destino del recién nacido', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='edad_gestacional_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Días de gestación', null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='edad_gestacional_semanas',
            field=models.PositiveIntegerField(blank=True, help_text='Semanas de gestación', null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='gases_cordon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='hora_nacimiento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='int_causal_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='interno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='lactancia_antes_media_hora',
            field=models.BooleanField(default=False, help_text='Lact. antes 1/2 hr'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='malformacion_congenita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='profesional_vacuna_vhb',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='profilaxis_ocular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='reanimacion_avanzada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='reanimacion_basica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Intersexual')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='tipo_parto',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('cesarea', 'Cesárea'), ('instrumental', 'Instrumental')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='vacuna_bcg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='vacuna_hepatitis_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso en gramos', max_digits=5),
        ),
    ]
