# Generated by Django 5.2.8 on 2025-11-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_cesfam_paciente_comuna_paciente_es_migrante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='hepatitis_b_profilaxis_completa',
            field=models.BooleanField(default=False, help_text='Profilaxis Completa (Sí/No)'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='lactancia_antes_60min',
            field=models.BooleanField(default=False, help_text="Lact. antes 60'"),
        ),
    ]
