# Generated by Django 5.2.8 on 2025-11-20 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_paciente_cesfam_paciente_comuna_paciente_es_migrante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_admision', models.DateTimeField(auto_now_add=True)),
                ('tipo_admision', models.CharField(choices=[('urgencia', 'Urgencia'), ('programada', 'Programada'), ('parto', 'Parto'), ('consulta', 'Consulta')], default='consulta', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('motivo_admision', models.TextField(help_text='Motivo de la admisión')),
                ('servicio', models.CharField(blank=True, help_text='Servicio o área de atención', max_length=100, null=True)),
                ('medico_responsable', models.CharField(blank=True, max_length=120, null=True)),
                ('numero_habitacion', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='pacientes.paciente')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admisión',
                'verbose_name_plural': 'Admisiones',
                'ordering': ['-fecha_admision'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total a pagar', max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado hasta ahora', max_digits=10)),
                ('monto_pendiente', models.DecimalField(decimal_places=2, help_text='Monto pendiente', max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('fonasa', 'FONASA'), ('isapre', 'ISAPRE'), ('particular', 'Particular')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('concepto', models.CharField(help_text='Concepto del pago (consulta, procedimiento, etc.)', max_length=255)),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número de comprobante o boleta', max_length=50, null=True)),
                ('numero_transaccion', models.CharField(blank=True, help_text='Número de transacción bancaria', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del pago', null=True)),
                ('admision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='administrativos.admision')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pacientes.paciente')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
