# Generated by Django 5.2.8 on 2025-11-20 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativos', '0001_initial'),
        ('pacientes', '0003_paciente_hepatitis_b_profilaxis_completa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('tipo_alta', models.CharField(choices=[('alta_medica', 'Alta Médica'), ('alta_voluntaria', 'Alta Voluntaria'), ('traslado', 'Traslado'), ('fallecimiento', 'Fallecimiento'), ('alta_administrativa', 'Alta Administrativa')], default='alta_medica', max_length=20)),
                ('estado_episodio', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('documento_alta_entregado', models.BooleanField(default=False, help_text='Documento de alta entregado a la familia')),
                ('certificado_defuncion_entregado', models.BooleanField(default=False, help_text='Certificado de defunción entregado (si aplica)')),
                ('informe_medico_entregado', models.BooleanField(default=False, help_text='Informe médico entregado')),
                ('recetas_entregadas', models.BooleanField(default=False, help_text='Recetas médicas entregadas')),
                ('otros_documentos', models.TextField(blank=True, help_text='Otros documentos entregados', null=True)),
                ('fecha_entrega_documentos', models.DateTimeField(blank=True, null=True)),
                ('persona_que_recibio', models.CharField(blank=True, help_text='Nombre de la persona que recibió los documentos', max_length=200, null=True)),
                ('pagos_completados', models.BooleanField(default=False, help_text='Pagos completados')),
                ('facturacion_cerrada', models.BooleanField(default=False, help_text='Facturación cerrada')),
                ('habitacion_liberada', models.BooleanField(default=False, help_text='Habitación liberada')),
                ('expediente_clinico_archivado', models.BooleanField(default=False, help_text='Expediente clínico archivado')),
                ('notificaciones_enviadas', models.BooleanField(default=False, help_text='Notificaciones enviadas')),
                ('tramites_adicionales', models.TextField(blank=True, help_text='Trámites administrativos adicionales realizados', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('admision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alta_egreso', to='administrativos.admision')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altas_egresos', to='pacientes.paciente')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alta y Egreso',
                'verbose_name_plural': 'Altas y Egresos',
                'ordering': ['-fecha_alta'],
            },
        ),
    ]
